version: "3.3"

services:
  invitation_frontend_app:
    container_name: invitation_frontend
    build:
      context: .
      dockerfile: Dockerfile
      #target: development
    volumes:
      - .:/app
      # - './src:/app/src'
      # - '/app/node_modules'
    ports:
      - 3076:3000
    environment:
      - NODE_ENV=production
      # - BACKEND_URL=http://192.168.10.51:8076/