version: "3.3"

services:
  app:
    container_name: invitation_frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
      #target: development
    volumes:
      - './src:/app/src'
      - '/app/node_modules'
    ports:
      - 3076:3000
    environment:
      - BACKEND_URL=http://192.168.10.51:8076/